[package]
name = "tauri-plugin-macos-permissions"
version = "2.0.1"
authors = [ "ayangweb" ]
description = "Accessibility and full disk access for macOS can be checked and requested."
repository = "https://github.com/ayangweb/tauri-plugin-macos-permissions"
keywords = ["macos-permissions", "tauri", "tauri-plugin", "accessibility", "full-disk-access"]
license = "MIT"
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-macos-permissions"

[dependencies]
tauri = { version = "2.1.0" }
serde = "1.0"
thiserror = "2"

[build-dependencies]
tauri-plugin = { version = "2.0.2", features = ["build"] }

[target."cfg(target_os = \"macos\")".dependencies]
macos-accessibility-client = "0.0.1"
fs_extra = "1.3.0"
log = "0.4.22"