"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the plugin"
permissions = ["allow-check-accessibility-permissions", "allow-request-accessibility-permissions", "allow-check-full-disk-access-permissions", "allow-request-full-disk-access-permissions"]
